version: '3'
services:
  quetre:
    container_name: quetre
    image: quay.io/pussthecatorg/quetre:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:10050:3000"
    environment:
      - "NODE_ENV=production"
      - "PORT=3000"