version: '3'
services:
  searxng:
    container_name: searxng
    image: docker.io/searxng/searxng:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:10052:8080"
    environment:
      - "BASE_URL=http://localhost:10052/"
      - "INSTANCE_NAME=searxng"